### ISSUE TITLE
Failing to compile when trying to update from AUR

### ISSUE THREAD

**Issue by neurofire80** [hrkfdn/ncspot#719] opened 2022-01-22 15:01 UTC
Issue: 
Compile error when trying to update from AUR

**To Reproduce**
yay -Syyu

**Screenshots**

 Compiling ncspot v0.9.5 (/home/aurion/.cache/yay/ncspot/src/ncspot-0.9.5)
error: there is no argument named `content_len`
  --> src/ui/listview.rs:88:34
   |
88 |         log::info!("content len: {content_len}");
   |                                  ^^^^^^^^^^^^^

error: there is no argument named `loaded`
   --> src/ui/listview.rs:100:35
    |
100 |         log::info!("can paginate: {loaded}");
    |                                   ^^^^^^^^

error: could not compile `ncspot` due to 2 previous errors
==> ERROR: A failure occurred in build().
    Aborting...
 -> error making: ncspot

**System (please complete the following information):**
 - OS: Manjaro i3
 - Terminal: urxvt
 - Version: 0.9.5
 - Installed from: AUR

Thank you

**Comment by hrkfdn** [comment] 2022-01-22 15:06
Duplicate of #714 714

**Closed by hrkfdn** 2022-01-22 15:06 UTC
Labels: bug
