### ISSUE TITLE
Request: Easier navigation to Daily Mix, Discover Weekly etc.

### ISSUE THREAD

**Issue by m-squared96** [hrkfdn/ncspot#301] opened 2020-10-23 11:17 UTC
One area in which NCSpot is much harder to use than the vanilla Spotify app is when attempting to find playlists curated for the user by Spotify.

Typical examples of this would be the Daily Mix playlists, Discover Weekly etc. as well as the playlists Spotify creates summarising the user's listening habits for the year/decade etc. 

I would suggest breaking the Library > Playlist menu into two sections: 1. Playlists created/saved by the user and 2. Playlists curated by Spotify for the user. Currently this menu is made up completely of playlists created by the user.

**Comment by m-squared96** [comment] 2020-10-23 11:18
Would be happy to contribute some code, I have a little experience with Rust and regularly use NCSpot.

Really great project!

**Comment by hrkfdn** [comment] 2020-10-24 18:33
Hey! This would be nice, but from what I can tell the Spotify API does not expose the playlist type (curated vs. user playlist). Do you have an idea how to solve this?

**Comment by m-squared96** [comment] 2020-10-25 16:29
I'm new to the API myself and don't have a solution to hand. 

Naturally, I would start by looking for the creator of the playlist; on the Spotify Android app the creator of the Daily Mix playlists, for example, is listed as Spotify. It seems as though the relevant metadata to piece this together exists somewhere, however I don't know if this is exposed via the API.

A second potential approach would be a slightly hackier method, utilising simple string searching methods and/or regular expressions, but there are assumptions to be made for this approach that may or may not work.

I'll have a look at the API docs and see if there's a way around this.

**Comment by mtshrmn** [comment] 2020-11-05 18:44
Duplicate of #283

**Comment by mtshrmn** [comment] 2020-12-14 17:06
I've been trying to implement this feature, and I've come to a dead end. The access token needed for this API call is a different one which isn't provided by the API. 
The token which ncspot (and the rest of the documented API) operates on is retrieved from https://accounts.spotify.com/api/token.
For us to call [made-for-x](https://api.spotify.com/v1/views/made-for-x) we need to use a token from https://open.spotify.com/get_access_token which complicates stuff a lot. 

If anyone attempts this, FYI.

**Comment by hrkfdn** [comment] 2021-01-02 20:10
Thanks for the heads up. I'm closing this for now. We can reopen it once the API exists.

**Closed by hrkfdn** 2021-01-02 20:10 UTC

**Comment by Einenlum** [comment] 2022-02-02 11:47
FYI, not sure how it does, but [spotify-tui](https://github.com/Rigellute/spotify-tui) is able to get me some generated playlists (discover weekly, on repeat, daily drive…). Not sure how they do it, but it's also written in Rust. Maybe someone could find some solution there? (I'm not a Rust developer, so I'm not sure)
