### ISSUE TITLE
Using hjkl to navigate in context menus isn't responding

### ISSUE THREAD

**Issue by codecalec** [hrkfdn/ncspot#199] opened 2020-05-28 08:38 UTC
I'm looking in the keybindings and it seems like hjkl are set to the same action as Left, Down, Up and Right but they do not behave like arrow keys in context menu.

j and k do not move the selection vertically while the arrow keys work as expected.

Not sure if this is intended.

**Comment by hrkfdn** [comment] 2020-05-28 11:04
Closed as duplicate of #108

**Closed by hrkfdn** 2020-05-28 11:04 UTC
