### ISSUE TITLE
Tracks are not scrobbled to last.fm

### ISSUE THREAD

**Issue by GaffaSnobb** [hrkfdn/ncspot#1034] opened 2023-01-19 11:31 UTC
**Describe the bug**
Music I listen to with ncspot does not scrobble to last.fm. Music I listen to in the Spotify macOS app scrobbles to last.fm. I tested this back to back just now on the same computer with the same account on the same network just a few seconds apart.

I thought this might be a bug since linking your Spotify account to your last.fm account does not happen on an app level but on an account level. I dont type my last.fm credentials into the Spotify application, and last.fm scrobbling happens on my phone (iOS), Mac, Windows computer and web browser without needing to configure these separately.

**To Reproduce**
Play a song with ncspot and it wont scrobble.

**Expected behavior**
Songs played with ncspot should scrobble.

**System (please complete the following information):**
 - OS: macOS 13.0.1
 - Terminal: iTerm
 - Version: ncspot 0.12.0
 - Installed from: brew

**Comment by hrkfdn** [comment] 2023-02-19 13:08
This is a problem in librespot that may be fixed in the future as it doesn't notify the Spotify endpoint when a track finished played. For now you could use MPRIS based scrobblers. See also:
- https://github.com/librespot-org/librespot/issues/913
- https://github.com/hrkfdn/ncspot/issues/639

Closing as duplicate of #639

**Closed by hrkfdn** 2023-02-19 13:08 UTC
Labels: bug
