### ISSUE TITLE
ncspot doesn't seem to support terminal resizing

### ISSUE THREAD

**Issue by invakid404** [hrkfdn/ncspot#274] opened 2020-09-27 19:01 UTC
I noticed ncspot's UI messes up if the terminal window is resized, so I was wondering if it's possible to make it recalculate its UI upon resizing, not just upon startup.

**Comment by BachoSeven** [comment] 2020-09-28 12:49
- What terminal emulator are you using? What is your shell? Give some more details on your setup, in order to make it reproducible.
- Could you attach a screenshot to show exactly how the UI gets messed up?

**Comment by hrkfdn** [comment] 2020-09-28 15:25
This is the behavior I face: When resizing, ncspot doesn't immediately redraw. As soon as there is key input, the UI is redrawn and fits again. Is this what you're facing, or is the behavior different with your setup?

I guess ncspot could listen for resize events and redraw the UI as a consequence.

**Comment by invakid404** [comment] 2020-09-28 17:28
ncspot doesn't seem to redraw at all upon resizing/key input, at least for me.

I'm using kitty as my terminal emulator, bash as my shell, xmonad as my WM.

the UI messes up severely, screenshots related. first one is before, second one is after resizing

![image](https://user-images.githubusercontent.com/38114607/94465810-240fc680-01c9-11eb-8fc7-f2482f04d51c.png)
![image](https://user-images.githubusercontent.com/38114607/94465827-2a9e3e00-01c9-11eb-9f84-833ee7a13028.png)

**Comment by invakid404** [comment] 2020-09-28 17:31
and yes - redrawing the UI upon receiving a resize event sounds like the way to go ^

**Comment by hrkfdn** [comment] 2020-09-28 20:21
> I guess ncspot could listen for resize events and redraw the UI as a consequence.

I just checked and this seems to already be the default behavior with `gnome-terminal`. Could this be a problem with Kitty?

**Comment by mtshrmn** [comment] 2020-09-29 10:34
Checked with kitty 0.18.3 and the latest ncspot commit with the default features. Same behavior as gnome-terminal.

**Comment by BachoSeven** [comment] 2020-09-29 10:52
I also cannot reproduce this with same kitty version, resizing redraws the UI without needing to input any key.

**Comment by invakid404** [comment] 2020-09-29 13:23
> Checked with kitty 0.18.3 and the latest ncspot commit with the default features. Same behavior as gnome-terminal.

I'm running 0.18.3 as well, which makes me believe xmonad could be the culprit?

**Comment by mtshrmn** [comment] 2020-09-29 13:43
> xmonad could be the culprit?

I've tried the same setup as before, and I was unable to reproduce the problem with a simple xmonad [configuration](https://wiki.archlinux.org/index.php/xmonad#A_base_desktop_configuration) but to no avail. 
This could happen because some package got compiled with different flags and it is causing the error. I'm not knowledgeable enough with gentoo (I assume because of the icon from the screenshot), so I can't help any further.

**Comment by invakid404** [comment] 2020-09-29 13:49
I mean yeah, I just tried ncspot on my laptop running Cinnamon, everything seems to be fine, so I'll have to track down the issue on my end, maybe I should have done that in the first place...

**Comment by invakid404** [comment] 2020-09-29 14:27
hmm, this is still interesting though. I noticed an obvious issue on my end - I was actually relying on an unofficial Gentoo overlay to provide me with the ncspot ebuild, and it turns out the version it provides is painfully old. I did patch together an ebuild for ncspot v0.2.2, but it still doesn't resize properly.

**Comment by invakid404** [comment] 2020-09-30 07:37
Checked the exact same ebuild for ncspot on my laptop in the same version of kitty, resizing seems fine... Conclusion: (my) xmonad seems to actually be the issue. I'll do some more testing once I am back on my PC and see what I can figure out.

**Comment by hrkfdn** [comment] 2020-09-30 14:27
Thanks for the input everyone. Then I'll close this as it does not seem to be an ncspot issue.

**Closed by hrkfdn** 2020-09-30 14:27 UTC
