### ISSUE TITLE
Problem compiling ncspot on KDE Neon 5.19

### ISSUE THREAD

**Issue by swarfega** [hrkfdn/ncspot#245] opened 2020-08-11 22:18 UTC
I am having problems installing ncspot (see code below). It installed fine on Manjaro KDE 20, so I'm not sure what I'm missing.

Operating System: KDE neon 5.19
KDE Plasma Version: 5.19.4
KDE Frameworks Version: 5.72.0
Qt Version: 5.14.2
Kernel Version: 5.7.10-050710-generic
OS Type: 64-bit
Processors: 8 × Intel® Core™ i7-6700K CPU @ 4.00GHz
Memory: 31.2 GiB of RAM
Graphics Processor: NV134

`error[E0599]: no method named `compat` found for type `u64` in the current scope
   --> /home/swarfega/.cargo/registry/src/github.com-1ecc6299db9ec823/ncspot-0.2.0/src/spotify.rs:166:85
    |
166 | ...                   self.play_task = Box::pin(self.player.load(id, true, 0).compat());
    |                                                                               ^^^^^^ method not found in `u64`
    |
    = note: the method `compat` exists but the following trait bounds were not satisfied:
            `u64: futures::future::Future`
            which is required by `u64: futures::compat::Future01CompatExt`
            `u64: futures::stream::Stream`
            which is required by `u64: futures::compat::Stream01CompatExt`
            `&u64: futures::future::Future`
            which is required by `&u64: futures::compat::Future01CompatExt`
            `&u64: futures::stream::Stream`
            which is required by `&u64: futures::compat::Stream01CompatExt`
            `&mut u64: futures::future::Future`
            which is required by `&mut u64: futures::compat::Future01CompatExt`
            `&mut u64: futures::stream::Stream`
            which is required by `&mut u64: futures::compat::Stream01CompatExt`

error[E0063]: missing field `gapless` in initializer of `librespot_playback::config::PlayerConfig`
   --> /home/swarfega/.cargo/registry/src/github.com-1ecc6299db9ec823/ncspot-0.2.0/src/spotify.rs:408:29
    |
408 |         let player_config = PlayerConfig {
    |                             ^^^^^^^^^^^^ missing `gapless`

error: aborting due to 2 previous errors

Some errors have detailed explanations: E0063, E0599.
For more information about an error, try `rustc --explain E0063`.
error: failed to compile `ncspot v0.2.0`, intermediate artifacts can be found at `/tmp/cargo-installNxuEsz`

Caused by:
  could not compile `ncspot`.

To learn more, run the command again with --verbose.`

**Comment by avma** [comment] 2020-08-12 09:53
I'm Getting the same errors on Linux mint 20:
Operating System: Linux Mint 20
Kernel: Linux 5.4.0-42-generic
Architecture: x86-64

`Compiling ncspot v0.2.0
error[E0599]: no method named `compat` found for type `u64` in the current scope
   --> /home/avi/.cargo/registry/src/github.com-1ecc6299db9ec823/ncspot-0.2.0/src/spotify.rs:166:85
    |
166 | ...                   self.play_task = Box::pin(self.player.load(id, true, 0).compat());
    |                                                                               ^^^^^^ method not found in `u64`
    |
    = note: the method `compat` exists but the following trait bounds were not satisfied:
            `u64: futures::future::Future`
            which is required by `u64: futures::compat::Future01CompatExt`
            `u64: futures::stream::Stream`
            which is required by `u64: futures::compat::Stream01CompatExt`
            `&u64: futures::future::Future`
            which is required by `&u64: futures::compat::Future01CompatExt`
            `&u64: futures::stream::Stream`
            which is required by `&u64: futures::compat::Stream01CompatExt`
            `&mut u64: futures::future::Future`
            which is required by `&mut u64: futures::compat::Future01CompatExt`
            `&mut u64: futures::stream::Stream`
            which is required by `&mut u64: futures::compat::Stream01CompatExt`

error[E0063]: missing field `gapless` in initializer of `librespot_playback::config::PlayerConfig`
   --> /home/avi/.cargo/registry/src/github.com-1ecc6299db9ec823/ncspot-0.2.0/src/spotify.rs:408:29
    |
408 |         let player_config = PlayerConfig {
    |                             ^^^^^^^^^^^^ missing `gapless`

error: aborting due to 2 previous errors

Some errors have detailed explanations: E0063, E0599.
For more information about an error, try `rustc --explain E0063`.
error: failed to compile `ncspot v0.2.0`, intermediate artifacts can be found at `/tmp/cargo-installibIhVZ`

Caused by:
  could not compile `ncspot`.

To learn more, run the command again with --verbose.
`

**Comment by swarfega** [comment] 2020-08-12 10:35
I have since discovered that you need to do cargo build --release. But for some reason it installs the executable to /root/.cargo/bin, so copy it to /usr/bin which will then load.

**Comment by avma** [comment] 2020-08-12 12:07
I ran cargo build --release as you suggested and build did not end with errors, however   i could not find  /root/.cargo/bin on my system nor was I able to find any ncspot executable. So I really do not know where that build went...

**Comment by swarfega** [comment] 2020-08-12 12:28
You could try installing it in snap (which is out-dated)  then rebuild your local one.

**Comment by avma** [comment] 2020-08-13 08:17
Thanks, it worked, but still I think the normal install should be fixed...

**Comment by hrkfdn** [comment] 2020-08-13 08:46
Please try with the latest release

**Comment by avma** [comment] 2020-08-13 08:59
OK, i think i found the problem. 
just added 'gapless' to the file  /.cargo/registry/src/github.com-1ecc6299db9ec823/ncspot-0.2.0/src/spotify.rs
line: 408
column: 29
like so: 
`{
        let player_config = PlayerConfig {
            bitrate: Bitrate::Bitrate320::gapless,
            normalisation: cfg.volnorm.unwrap_or(false),
            normalisation_pregain: cfg.volnorm_pregain.unwrap_or(0.0),
        };`

now install ends without any errors...

**Comment by avma** [comment] 2020-08-15 06:01
Thanks' works fine now...

**Comment by swarfega** [comment] 2020-08-15 07:39
Mine works too, thanks. So whats new in 2.1?

**Comment by Bettehem** [comment] 2020-08-15 08:03
> Mine works too, thanks. So whats new in 2.1?

https://github.com/hrkfdn/ncspot/releases

**Closed** 2020-08-15 21:13 UTC
