### ISSUE TITLE
failed to compile

### ISSUE THREAD

**Issue by GiveMeFox** [hrkfdn/ncspot#1181] opened 2023-06-01 16:55 UTC
**Describe the bug**
errors while compiling

**To Reproduce**
cargo install ncspot

**Expected behavior**
i expected for it to compile without any errors

**Screenshots**
![image](https://github.com/hrkfdn/ncspot/assets/74460065/9986f8c3-0b94-4e24-a5bc-cd0d9f86dbe0)

**System (please complete the following information):**
 - OS: 6.3.4-arch1-1
 - Terminal: kitty
 - Version: ncspot v0.13.2
 - Installed from: cargo

**Backtrace/Debug log**
```
error[E0599]: no method named `as_millis` found for struct `chrono::Duration` in the current scope
  --> /home/sadperson/.cargo/registry/src/github.com-1ecc6299db9ec823/ncspot-0.13.2/src/model/episode.rs:36:40
   |
36 |             duration: episode.duration.as_millis() as u32,
   |                                        ^^^^^^^^^ method not found in `Duration`

error[E0599]: no method named `as_millis` found for struct `chrono::Duration` in the current scope
  --> /home/sadperson/.cargo/registry/src/github.com-1ecc6299db9ec823/ncspot-0.13.2/src/model/episode.rs:52:40
   |
52 |             duration: episode.duration.as_millis() as u32,
   |                                        ^^^^^^^^^ method not found in `Duration`

error[E0599]: no method named `as_millis` found for struct `chrono::Duration` in the current scope
  --> /home/sadperson/.cargo/registry/src/github.com-1ecc6299db9ec823/ncspot-0.13.2/src/model/track.rs:62:38
   |
62 |             duration: track.duration.as_millis() as u32,
   |                                      ^^^^^^^^^ method not found in `Duration`

error[E0599]: no method named `as_millis` found for struct `chrono::Duration` in the current scope
  --> /home/sadperson/.cargo/registry/src/github.com-1ecc6299db9ec823/ncspot-0.13.2/src/model/track.rs:99:38
   |
99 |             duration: track.duration.as_millis() as u32,
   |                                      ^^^^^^^^^ method not found in `Duration`

error[E0599]: no method named `as_millis` found for struct `chrono::Duration` in the current scope
   --> /home/sadperson/.cargo/registry/src/github.com-1ecc6299db9ec823/ncspot-0.13.2/src/model/track.rs:138:38
    |
138 |             duration: track.duration.as_millis() as u32,
    |                                      ^^^^^^^^^ method not found in `Duration`

error[E0308]: mismatched types
   --> /home/sadperson/.cargo/registry/src/github.com-1ecc6299db9ec823/ncspot-0.13.2/src/spotify_api.rs:162:17
    |
159 |             api.playlist_add_items(
    |                 ------------------ arguments to this method are incorrect
...
162 |                 position,
    |                 ^^^^^^^^ expected `Option<Duration>`, found `Option<i32>`
    |
    = note: expected enum `std::option::Option<chrono::Duration>`
               found enum `std::option::Option<i32>`
note: method defined here
   --> /home/sadperson/.cargo/registry/src/github.com-1ecc6299db9ec823/rspotify-0.11.7/src/clients/oauth.rs:300:14
    |
300 |     async fn playlist_add_items<'a>(
    |              ^^^^^^^^^^^^^^^^^^

Some errors have detailed explanations: E0308, E0599.
For more information about an error, try `rustc --explain E0308`.
error: could not compile `ncspot` due to 6 previous errors
error: failed to compile `ncspot v0.13.2`, intermediate artifacts can be found at `/tmp/cargo-installKY55IA`
```

Instructions on how to capture debug logs: https://github.com/hrkfdn/ncspot#debugging

For backtraces, make sure you run a debug build of ncspot, e.g. by running the
command mentioned in the [compilation
instructions](https://github.com/hrkfdn/ncspot#compiling).  You can find the
latest backtrace at `~/.cache/ncspot/backtrace.log`.

**Additional context**

**Comment by hrkfdn** [comment] 2023-06-01 19:14
Could you try building with `cargo install --locked ncspot`?

**Comment by 0xJepsen** [comment] 2023-06-08 02:45
with locked this solves this for me

**Comment by drjaska** [comment] 2023-06-15 23:55
I wasn't aware of this issue when opening https://github.com/hrkfdn/ncspot/issues/1193 as a duplicate of this issue, that issue was marked as completed and closed but this is still open.

**Closed** 2023-06-17 11:50 UTC
Labels: bug
