### ISSUE TITLE
Spotify connect support

### ISSUE THREAD

**Issue by febs** [hrkfdn/ncspot#1524] opened 2024-10-01 10:27 UTC
I could not find any documentation about how to stream any music to a spotify connect device, nor I could find anyting in the sample configuration file. 

If that is not a feature of ncspot, please consider adding it. :-)

Thanks,

**Comment by Bettehem** [comment] 2024-10-05 08:34
Duplicate of [#83](https://github.com/hrkfdn/ncspot/issues/83)

**Closed** 2024-11-01 13:08 UTC
Labels: enhancement
