### ISSUE TITLE
internet drop issue, ncspot not playing any track/playlist after connection restored

### ISSUE THREAD

**Issue by inomoz** [hrkfdn/ncspot#125] opened 2020-02-04 23:02 UTC
Sometimes (some providers even force drop internet each days) I have internet connections issues, usually it just for few seconds, but then ncspot not playing any track, seems It can't reconnect to spotify?

Log file attached (error in end of file).
```
[2020-02-05][01:58:43] [librespot_playback::player] [DEBUG] Shutting down player thread ...
[2020-02-05][01:58:43] [tokio_threadpool::pool] [TRACE] shutdown; state=pool::State { lifecycle: Running, num_futures: 0 }
[2020-02-05][01:58:43] [tokio_threadpool::pool] [TRACE]   -> transitioned to shutdown
[2020-02-05][01:58:43] [tokio_threadpool::pool] [TRACE]   -> shutting down workers
[2020-02-05][01:58:43] [ncspot::mpris] [DEBUG] mpris PropertiesChanged: status Playing, track: Some((Burgundy Skies - Safe And Sound (Some("61nBe7BiDRiwqSNZfAjswA"))))
[2020-02-05][01:58:43] [ncspot::mpris] [DEBUG] mpris PropertiesChanged: status Stopped, track: Some((Burgundy Skies - Safe And Sound (Some("61nBe7BiDRiwqSNZfAjswA"))))
[2020-02-05][01:58:52] [tokio_reactor] [TRACE] loop process - 0 events, 0.000s
...
[2020-02-05][01:58:53] [hyper::client::pool] [TRACE] idle interval checking for expired
[2020-02-05][01:58:53] [tokio_reactor] [TRACE] event Readable Token(4194303)
[2020-02-05][01:58:53] [tokio_reactor] [TRACE] loop process - 1 events, 0.000s
....
[2020-02-05][02:00:23] [tokio_reactor] [TRACE] loop process - 0 events, 0.000s
[2020-02-05][02:00:23] [hyper::client::pool] [TRACE] idle interval checking for expired
[2020-02-05][02:00:23] [hyper::client::pool] [TRACE] idle interval evicting expired for "https://api.spotify.com"
[2020-02-05][02:00:23] [hyper::client::pool] [TRACE] idle interval evicting expired for "https://api.spotify.com"
...
[2020-02-05][02:00:23] [tokio_reactor] [TRACE] event Readable Token(4194303)
[2020-02-05][02:00:23] [tokio_reactor] [TRACE] loop process - 1 events, 0.000s
[2020-02-05][02:00:23] [tokio_reactor::registration] [DEBUG] scheduling Read for: 1
[2020-02-05][02:00:23] [hyper::proto::h1::dispatch] [TRACE] client tx closed
[2020-02-05][02:00:23] [hyper::proto::h1::conn] [TRACE] State::close_read()
[2020-02-05][02:00:23] [hyper::proto::h1::conn] [TRACE] State::close_write()
[2020-02-05][02:00:23] [hyper::proto::h1::conn] [TRACE] flushed({role=client}): State { reading: Closed, writing: Closed, keep_alive: Disabled }
[2020-02-05][02:00:23] [hyper::proto::h1::conn] [TRACE] shut down IO complete
[2020-02-05][02:00:23] [mio::poll] [TRACE] deregistering handle with poller
[2020-02-05][02:00:23] [tokio_reactor] [DEBUG] dropping I/O source: 1
[2020-02-05][02:00:23] [want] [TRACE] signal: Closed
[2020-02-05][02:00:23] [tokio_reactor::registration] [DEBUG] scheduling Read for: 2
[2020-02-05][02:00:23] [hyper::proto::h1::dispatch] [TRACE] client tx closed
[2020-02-05][02:00:23] [hyper::proto::h1::conn] [TRACE] State::close_read()
[2020-02-05][02:00:23] [hyper::proto::h1::conn] [TRACE] State::close_write()
[2020-02-05][02:00:23] [hyper::proto::h1::conn] [TRACE] flushed({role=client}): State { reading: Closed, writing: Closed, keep_alive: Disabled }
[2020-02-05][02:00:23] [hyper::proto::h1::conn] [TRACE] shut down IO complete
[2020-02-05][02:00:23] [mio::poll] [TRACE] deregistering handle with poller
[2020-02-05][02:00:23] [tokio_reactor] [DEBUG] dropping I/O source: 2
[2020-02-05][02:00:23] [want] [TRACE] signal: Closed
[2020-02-05][02:00:23] [tokio_reactor::registration] [DEBUG] scheduling Read for: 3
[2020-02-05][02:00:23] [hyper::proto::h1::dispatch] [TRACE] client tx closed
[2020-02-05][02:00:23] [hyper::proto::h1::conn] [TRACE] State::close_read()
[2020-02-05][02:00:23] [hyper::proto::h1::conn] [TRACE] State::close_write()
[2020-02-05][02:00:23] [hyper::proto::h1::conn] [TRACE] flushed({role=client}): State { reading: Closed, writing: Closed, keep_alive: Disabled }
[2020-02-05][02:00:23] [hyper::proto::h1::conn] [TRACE] shut down IO complete
[2020-02-05][02:00:23] [mio::poll] [TRACE] deregistering handle with poller
[2020-02-05][02:00:23] [tokio_reactor] [DEBUG] dropping I/O source: 3
[2020-02-05][02:00:23] [want] [TRACE] signal: Closed
[2020-02-05][02:00:23] [tokio_reactor::registration] [DEBUG] scheduling Read for: 0
[2020-02-05][02:00:23] [hyper::proto::h1::dispatch] [TRACE] client tx closed
[2020-02-05][02:00:23] [hyper::proto::h1::conn] [TRACE] State::close_read()
[2020-02-05][02:00:23] [hyper::proto::h1::conn] [TRACE] State::close_write()
[2020-02-05][02:00:23] [hyper::proto::h1::conn] [TRACE] flushed({role=client}): State { reading: Closed, writing: Closed, keep_alive: Disabled }
[2020-02-05][02:00:23] [hyper::proto::h1::conn] [TRACE] shut down IO complete
[2020-02-05][02:00:23] [mio::poll] [TRACE] deregistering handle with poller
[2020-02-05][02:00:23] [tokio_reactor] [DEBUG] dropping I/O source: 0
[2020-02-05][02:00:23] [want] [TRACE] signal: Closed
[2020-02-05][02:00:23] [tokio_reactor] [TRACE] loop process - 0 events, 0.000s
...
[2020-02-05][02:01:53] [tokio_reactor] [TRACE] loop process - 0 events, 0.000s
[2020-02-05][02:01:53] [hyper::client::pool] [TRACE] idle interval checking for expired
[2020-02-05][02:01:53] [tokio_reactor] [TRACE] event Readable Token(4194303)
[2020-02-05][02:01:53] [tokio_reactor] [TRACE] loop process - 1 events, 0.000s
[2020-02-05][02:01:53] [tokio_reactor] [TRACE] loop process - 0 events, 0.000s
```
[ncspot.log](https://github.com/hrkfdn/ncspot/files/4156580/ncspot.log)

**Comment by hrkfdn** [comment] 2020-02-05 12:48
Which version is this? I recently updated librespot in `master` which had some changes for this: https://github.com/librespot-org/librespot/pull/427

**Comment by inomoz** [comment] 2020-02-05 12:54
![image](https://user-images.githubusercontent.com/3938577/73843428-b07f0a80-482f-11ea-9198-97fa154445c6.png)
```
ncspot 0.1.1
```

I have build it yesterday.

**Comment by Zocker1999NET** [comment] 2020-03-02 10:22
@inomoz Does ncspot show in the UI that it is still pretend playing a song but without an output or does the UI refuse to play any song?
After 2 or 3 songs ncspot refuses to play any song but the UI pretends it is still playing. Only a restart helps.

**Comment by inomoz** [comment] 2020-03-02 10:27
> @inomoz Does ncspot show in the UI that it is still pretend playing a song but without an output or does the UI refuse to play any song?

Yes UI showing it's still playing, but it not true.

**Comment by hrkfdn** [comment] 2020-06-16 22:46
Duplicate of https://github.com/hrkfdn/ncspot/issues/192

**Closed by hrkfdn** 2020-06-16 22:46 UTC
