### ISSUE TITLE
Facebook login is no longer supported by this version of Spotify. Download the latest version to log in.

### ISSUE THREAD

**Issue by ParaskItweb** [hrkfdn/ncspot#435] opened 2021-02-20 05:37 UTC
I have ncspot version 0.4.0, Whenever I am opening <Login with Facebook>. I am getting this error in the browser for authentication.

**Comment by hrkfdn** [comment] 2021-02-21 17:19
Duplicate of #310

**Closed by hrkfdn** 2021-02-21 17:19 UTC
