### ISSUE TITLE
Error on Cargo install (libdbus-sys)

### ISSUE THREAD

**Issue by guiananias** [hrkfdn/ncspot#137] opened 2020-02-25 21:42 UTC
Hey,
I tried to install ncspot today and I ended up with this little mistake. I've been looking for possible solutions for a few hours but I haven't found anything.

The error follows:
```
error: failed to run custom build command for `libdbus-sys v0.2.1

Caused by:
  process didn't exit successfully: /tmp/cargo-installGB2KfH/release/build/libdbus-sys-bb4addb19021ccd2/build-script-build` (exit code: 101)
```
Do you have any idea how to solve it?

P.S: It's my first time installing ncspot

**Comment by josephkois** [comment] 2020-02-26 19:08
im getting the same error

**Comment by hrkfdn** [comment] 2020-02-27 07:22
Have you installed the libdbus development headers as described in the readme? Is there a more detailed log?

**Comment by guiananias** [comment] 2020-02-27 09:05
Yep, I installed libdbus that spoke in the README

I will not be able to help with a more detailed log because it is just this message that it returns to me but I did the test in another distro and can install it normally.

Maybe I will reinstall Mint, maybe it will work now

Thanks, bro

**Comment by hrkfdn** [comment] 2020-02-27 15:16
Closing this, as it's most likely due to missing dependencies and not a bug.

**Closed by hrkfdn** 2020-02-27 15:16 UTC
