### ISSUE TITLE
Can't continue to play after connecting/disconnecting VPN

### ISSUE THREAD

**Issue by ilyachch** [hrkfdn/ncspot#777] opened 2022-04-01 14:33 UTC
After connecting/disconnecting VPN (OpenVPN in my case) payback continues until cache loaded and nothing happens after it

1. Start playing any song
2. Turn on VPN connection
3. Try to go to next song or wait until current end

**Current behaviour**
Now playback can be returned only by restarting. I can go to recommendations, open my playlists and do anything else, but play tracks

**Expected behavior**
I think, it could take some time to reconnect, but playback should continue.

**System (please complete the following information):**
 - OS: Ubuntu Linux 20.04.3
 - Terminal: Alacritty
 - Version: 0.9.5
 - Installed from: snap

**Additional context**
`Shift+u`, `:reload` do not help

**Comment by im-n1** [comment] 2022-05-27 07:49
This issue bugs me since I started using ncspot (more than a year ago). It would be nice to have it fixed because once the connection changes ncspot crashes.

**Comment by hrkfdn** [comment] 2022-05-27 09:46
I would love to fix it, but I can't really handle connectivity issues if librespot can't detect them yet. This hasn't changed.

Duplicate of #628

**Closed by hrkfdn** 2022-05-27 09:46 UTC
Labels: bug
