### ISSUE TITLE
Can't install, librespot-protocol compile error

### ISSUE THREAD

**Issue by crashmaster** [hrkfdn/ncspot#179] opened 2020-04-16 07:49 UTC
Hello!

After installing the dependencies and executing `$HOME/.cargo/bin/cargo install ncspot` I got the following:
```
   Compiling librespot-protocol v0.1.1
error[E0308]: mismatched types
  --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/librespot-protocol-0.1.1/build.rs:45:39
   |
45 |         let p = parse_and_typecheck(&["proto"], &[src]).expect("protoc");
   |                                       ^^^^^^^ expected struct `std::path::Path`, found `str`
   |
   = note: expected reference `&std::path::Path`
              found reference `&'static str`

error[E0308]: mismatched types
  --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/librespot-protocol-0.1.1/build.rs:45:51
   |
45 |         let p = parse_and_typecheck(&["proto"], &[src]).expect("protoc");
   |                                                   ^^^ expected struct `std::path::Path`, found struct `std::string::String`
   |
   = note: expected reference `&std::path::Path`
              found reference `&std::string::String`

error: aborting due to 2 previous errors

```
Host:
cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=19.10
DISTRIB_CODENAME=eoan
DISTRIB_DESCRIPTION="Ubuntu 19.10"

(I get the very error on my Ubuntu 16.04 as well.)

Any hints, suggestions?

**Comment by g-bartoszek** [comment] 2020-04-17 20:18
cargo install tries to use protobuf-codegen-pure v2.14.0 which is not compatible with protobuf-codegen-pure v2.8.1 required by librespot-protocol. I guess that it is semantic versioning problem - there was a breaking change without a major version bump so cargo thinks it can use the newer version which is required by another dependency.

I managed to build ncspot by using a local librespot aligned to work with the newest protobuf-codegen-pure

**Comment by hrkfdn** [comment] 2020-04-17 20:35
Related: https://github.com/librespot-org/librespot/issues/460

**Comment by dmaglio** [comment] 2020-04-20 09:40
although https://github.com/librespot-org/librespot/issues/460 is closed it still does not go, it only works as a master with `` cargo build --release``` and `` cargo run````

**Comment by BachoSeven** [comment] 2020-04-23 15:05
I get the same errors as OP with `cargo install --git`

**Closed** 2020-04-23 18:44 UTC

**Comment by hrkfdn** [comment] 2020-04-23 19:09
Pushed a commit that should fix compilation until new librespot crates are published.

**Comment by cristianmiranda** [comment] 2020-04-26 16:16
Hi, I still experience the same issue. I'm installing using cargo, any updates on this?
Thanks!

**Comment by tshirtman** [comment] 2020-04-26 20:52
same here following the cargo installation instruction, currently building with:
`cargo install --git https://github.com/hrkfdn/ncspot` as suggested by the above comments, will update when it's done.

**Comment by hrkfdn** [comment] 2020-04-26 21:03
I just did a fresh `git clone` and ran `cargo build`, I can't reproduce it :thinking:

**Comment by tshirtman** [comment] 2020-04-26 21:18
yes, the git version works, i guess it's just that `cargo install ncspot` doesn't use that.

but that didn't resolve my sound problem, pulseaudio doesn't see ncspot, but that's another issue :|

**Comment by hrkfdn** [comment] 2020-04-27 09:27
Unfortunately I can not republish the version. I also currently can't publish a new release with the fix, as librespot has not published updated crates.

**Comment by hrkfdn** [comment] 2020-05-01 15:58
Just found out that you can tell cargo to use the lockfile, which should help, e.g. `cargo install ncspot --locked`
