### ISSUE TITLE
panic logging in

### ISSUE THREAD

**Issue by egtann** [hrkfdn/ncspot#136] opened 2020-02-25 16:55 UTC
Tried to boot ncspot this morning. I thought it was strange that I was asked to provide my password.

I provided my password then ncspot asked for the password again with `Failed to authenticate. Cannot read file from /home/{my_user_account}/.config/ncspot/credentials.toml`. When I select "Quit" I see this has been outputted to my terminal:

```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 61, kind: ConnectionRefused, message: "Connection refused" }', src/libcore/result.rs:1188:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
Didn't obtain any credentials
```

After this, `config.toml` exists but is empty.

Running ncspot 0.1.2 on OpenBSD -current.

**Comment by Hukadan** [comment] 2020-02-26 12:14
I can reproduce this on the 25-02-2020 snapshot using ncspot 0.1.2. The error message is
```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 60, kind: TimedOut, message: "Operation timed out" }', src/libcore/result.rs:1188:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 60, kind: TimedOut, message: "Operation timed out" }', src/libcore/result.rs:1188:5
Didn't obtain any credentials
```

The corresponding debug file (using `ncspot -d`) is here :
https://gist.github.com/Hukadan/90bb712c902490de971c991ef469e9c0

**Comment by hrkfdn** [comment] 2020-02-27 07:23
But the login itself does work correctly? The config deletion is already tracked here: https://github.com/hrkfdn/ncspot/issues/77

In your logs it seems it cannot resolve/connect to the Spotify servers.

**Comment by Hukadan** [comment] 2020-02-27 18:20
Trying again tonight, it just worked. May be a network problem on my side that triggered the removal of the config file.

Sorry for the noise.

**Comment by hrkfdn** [comment] 2020-02-28 10:18
Thanks for the feedback. It's still a bug that the file is deleted, but since that is tracked in #77, I'll close this issue.

**Closed by hrkfdn** 2020-02-28 10:18 UTC
