### ISSUE TITLE
Cannot compile v0.9.5

### ISSUE THREAD

**Issue by nloyola** [hrkfdn/ncspot#715] opened 2022-01-20 07:54 UTC
**Describe the bug**
Pulled tag v0.9.5 today, followed by command `cargo deb` and I got:

```
error: there is no argument named `content_len`
  --> src/ui/listview.rs:88:34
   |
88 |         log::info!("content len: {content_len}");
   |                                  ^^^^^^^^^^^^^

error: there is no argument named `loaded`
   --> src/ui/listview.rs:100:35
    |
100 |         log::info!("can paginate: {loaded}");
    |                                   ^^^^^^^^

error: could not compile `ncspot` due to 2 previous errors
```

**To Reproduce**
1. git checkout v0.9.5
2. cargo deb

**Expected behavior**
Expect the Debian package to be build without any compilation errors.

**Screenshots**
N/A

**System (please complete the following information):**
 - OS: Linux
 - Terminal:Alacritty
 - Version: v0.9.5
 - Installed from: N/A

**Backtrace/Debug log**
See above.

**Additional context**
N/A

**Comment by hrkfdn** [comment] 2022-01-20 09:26
You need Rust 1.58.0 to compile ncspot 0.9.5

**Comment by hrkfdn** [comment] 2022-01-20 09:27
Duplicate of #714

**Closed by hrkfdn** 2022-01-20 09:27 UTC
Labels: bug
