### ISSUE TITLE
Unable to update

### ISSUE THREAD

**Issue by Ramiferous** [hrkfdn/ncspot#418] opened 2021-02-02 04:05 UTC
ncspot 0.2.6 installed. When I try update with `cargo install ncspot` it fails when trying to build `cursive_core`

Output:

```
Compiling cursive_core v0.1.2
     Running `rustc --crate-name cursive_core --edition=2018 /home/david/.cargo/registry/src/github.com-1ecc6299db9ec823/cursive_core-0.1.2/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C opt-level=3 -C embed-bitcode=no -C metadata=1fb5a3501c627612 -C extra-filename=-1fb5a3501c627612 --out-dir /tmp/cargo-installoEFwKL/release/deps -L dependency=/tmp/cargo-installoEFwKL/release/deps --extern ahash=/tmp/cargo-installoEFwKL/release/deps/libahash-356767e161cd7804.rmeta --extern chrono=/tmp/cargo-installoEFwKL/release/deps/libchrono-7d2823f2f9122b2a.rmeta --extern crossbeam_channel=/tmp/cargo-installoEFwKL/release/deps/libcrossbeam_channel-63e233bc50165077.rmeta --extern enum_map=/tmp/cargo-installoEFwKL/release/deps/libenum_map-94b121b1955a19f2.rmeta --extern enumset=/tmp/cargo-installoEFwKL/release/deps/libenumset-3e2480a408da754e.rmeta --extern lazy_static=/tmp/cargo-installoEFwKL/release/deps/liblazy_static-49b79ac062ddc731.rmeta --extern libc=/tmp/cargo-installoEFwKL/release/deps/liblibc-6307381732dbad6c.rmeta --extern log=/tmp/cargo-installoEFwKL/release/deps/liblog-3217f079d39ad321.rmeta --extern num=/tmp/cargo-installoEFwKL/release/deps/libnum-a7c01d46a3351c20.rmeta --extern owning_ref=/tmp/cargo-installoEFwKL/release/deps/libowning_ref-77d3b858135b1dc0.rmeta --extern signal_hook=/tmp/cargo-installoEFwKL/release/deps/libsignal_hook-1e4312211a3224ad.rmeta --extern syn=/tmp/cargo-installoEFwKL/release/deps/libsyn-5855f0e58fd6c6d3.rmeta --extern unicode_segmentation=/tmp/cargo-installoEFwKL/release/deps/libunicode_segmentation-60dc348559656f17.rmeta --extern unicode_width=/tmp/cargo-installoEFwKL/release/deps/libunicode_width-3b67f6fb85ed7051.rmeta --extern xi_unicode=/tmp/cargo-installoEFwKL/release/deps/libxi_unicode-9c4c10134119c8ea.rmeta --cap-lints allow`
error[E0412]: cannot find type `EnumSet` in this scope
 --> /home/david/.cargo/registry/src/github.com-1ecc6299db9ec823/cursive_core-0.1.2/src/theme/effect.rs:4:10
  |
4 | #[derive(EnumSetType, Debug)]
  |          ^^^^^^^^^^^ not found in this scope
  |
  = note: this error originates in a derive macro (in Nightly builds, run with -Z macro-backtrace for more info)
help: consider importing one of these items
  |
1 | use crate::printer::EnumSet;
  |
1 | use enumset::EnumSet;
  |

error[E0422]: cannot find struct, variant or union type `EnumSet` in this scope
 --> /home/david/.cargo/registry/src/github.com-1ecc6299db9ec823/cursive_core-0.1.2/src/theme/effect.rs:4:10
  |
4 | #[derive(EnumSetType, Debug)]
  |          ^^^^^^^^^^^ not found in this scope
  |
  = note: this error originates in a derive macro (in Nightly builds, run with -Z macro-backtrace for more info)
help: consider importing one of these items
  |
1 | use crate::printer::EnumSet;
  |
1 | use enumset::EnumSet;
  |

   Compiling hyper v0.13.9
     Running `rustc --crate-name hyper --edition=2018 /home/david/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.13.9/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C opt-level=3 -C embed-bitcode=no --cfg 'feature="socket2"' --cfg 'feature="tcp"' -C metadata=26a7fc1192bce1b6 -C extra-filename=-26a7fc1192bce1b6 --out-dir /tmp/cargo-installoEFwKL/release/deps -L dependency=/tmp/cargo-installoEFwKL/release/deps --extern bytes=/tmp/cargo-installoEFwKL/release/deps/libbytes-79672dbdedbb9d45.rmeta --extern futures_channel=/tmp/cargo-installoEFwKL/release/deps/libfutures_channel-0d767a4033e7dbde.rmeta --extern futures_core=/tmp/cargo-installoEFwKL/release/deps/libfutures_core-8159ef3f172d3edb.rmeta --extern futures_util=/tmp/cargo-installoEFwKL/release/deps/libfutures_util-7a94ef0364a55ae0.rmeta --extern h2=/tmp/cargo-installoEFwKL/release/deps/libh2-9fa5929541d727d3.rmeta --extern http=/tmp/cargo-installoEFwKL/release/deps/libhttp-5a0def207214c612.rmeta --extern http_body=/tmp/cargo-installoEFwKL/release/deps/libhttp_body-f1fc5ad436ed8503.rmeta --extern httparse=/tmp/cargo-installoEFwKL/release/deps/libhttparse-0e52bb63737f864e.rmeta --extern httpdate=/tmp/cargo-installoEFwKL/release/deps/libhttpdate-10459aefb5ba577b.rmeta --extern itoa=/tmp/cargo-installoEFwKL/release/deps/libitoa-3a00ab445d20903c.rmeta --extern pin_project=/tmp/cargo-installoEFwKL/release/deps/libpin_project-884181be50dc73f7.rmeta --extern socket2=/tmp/cargo-installoEFwKL/release/deps/libsocket2-21c4ee61f041fadf.rmeta --extern tokio=/tmp/cargo-installoEFwKL/release/deps/libtokio-9daf90208839abe3.rmeta --extern tower_service=/tmp/cargo-installoEFwKL/release/deps/libtower_service-3af327557074b947.rmeta --extern tracing=/tmp/cargo-installoEFwKL/release/deps/libtracing-3fa3c47ad4ddff60.rmeta --extern want=/tmp/cargo-installoEFwKL/release/deps/libwant-33f1819c8efb26b9.rmeta --cap-lints allow`
error: aborting due to 2 previous errors

Some errors have detailed explanations: E0412, E0422.
For more information about an error, try `rustc --explain E0412`.
error: could not compile `cursive_core`

Caused by:
  process didn't exit successfully: `rustc --crate-name cursive_core --edition=2018 /home/david/.cargo/registry/src/github.com-1ecc6299db9ec823/cursive_core-0.1.2/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C opt-level=3 -C embed-bitcode=no -C metadata=1fb5a3501c627612 -C extra-filename=-1fb5a3501c627612 --out-dir /tmp/cargo-installoEFwKL/release/deps -L dependency=/tmp/cargo-installoEFwKL/release/deps --extern ahash=/tmp/cargo-installoEFwKL/release/deps/libahash-356767e161cd7804.rmeta --extern chrono=/tmp/cargo-installoEFwKL/release/deps/libchrono-7d2823f2f9122b2a.rmeta --extern crossbeam_channel=/tmp/cargo-installoEFwKL/release/deps/libcrossbeam_channel-63e233bc50165077.rmeta --extern enum_map=/tmp/cargo-installoEFwKL/release/deps/libenum_map-94b121b1955a19f2.rmeta --extern enumset=/tmp/cargo-installoEFwKL/release/deps/libenumset-3e2480a408da754e.rmeta --extern lazy_static=/tmp/cargo-installoEFwKL/release/deps/liblazy_static-49b79ac062ddc731.rmeta --extern libc=/tmp/cargo-installoEFwKL/release/deps/liblibc-6307381732dbad6c.rmeta --extern log=/tmp/cargo-installoEFwKL/release/deps/liblog-3217f079d39ad321.rmeta --extern num=/tmp/cargo-installoEFwKL/release/deps/libnum-a7c01d46a3351c20.rmeta --extern owning_ref=/tmp/cargo-installoEFwKL/release/deps/libowning_ref-77d3b858135b1dc0.rmeta --extern signal_hook=/tmp/cargo-installoEFwKL/release/deps/libsignal_hook-1e4312211a3224ad.rmeta --extern syn=/tmp/cargo-installoEFwKL/release/deps/libsyn-5855f0e58fd6c6d3.rmeta --extern unicode_segmentation=/tmp/cargo-installoEFwKL/release/deps/libunicode_segmentation-60dc348559656f17.rmeta --extern unicode_width=/tmp/cargo-installoEFwKL/release/deps/libunicode_width-3b67f6fb85ed7051.rmeta --extern xi_unicode=/tmp/cargo-installoEFwKL/release/deps/libxi_unicode-9c4c10134119c8ea.rmeta --cap-lints allow` (exit code: 1)
warning: build failed, waiting for other jobs to finish...
error: failed to compile `ncspot v0.3.0`, intermediate artifacts can be found at `/tmp/cargo-installoEFwKL`

Caused by:
  build failed
```

The output of `rustc --explain E0412` is below:

```
// or:

trait Foo {
    fn bar(N); // error: type name `N` is not in scope
}

// or:

fn foo(x: T) {} // type name `T` is not in scope
```

To fix this error, please verify you didn't misspell the type name, you did
declare it or imported it into the scope. Examples:

```
struct Something;

impl Something {} // ok!

// or:

trait Foo {
    type N;

    fn bar(_: Self::N); // ok!
}

// or:

fn foo<T>(x: T) {} // ok!
```

Another case that causes this error is when a type is imported into a parent
module. To fix this, you can follow the suggestion and use File directly or
`use super::File;` which will import the types from the parent namespace. An
example that causes this error is below:

```
use std::fs::File;

mod foo {
    fn some_function(f: File) {}
}
```

```
use std::fs::File;

mod foo {
    // either
    use super::File;
    // or
    // use std::fs::File;
    fn foo(f: File) {}
}
```
(END)
```

**Comment by hrkfdn** [comment] 2021-02-02 15:30
Duplicate of #416

**Closed by hrkfdn** 2021-02-02 15:30 UTC

**Comment by hrkfdn** [comment] 2021-02-03 09:20
I have just published a new release. Does that fix it?

**Comment by Ramiferous** [comment] 2021-02-04 04:34
Yep, that fixed it! Thanks
