### ISSUE TITLE
program not compile on new version

### ISSUE THREAD

**Issue by valtanders** [hrkfdn/ncspot#720] opened 2022-01-23 16:04 UTC
Description: error when try to compile

when i try to upgrade to the new version, there is 2 errors on listview.rs, line 88 and 100, the parameters on the log are wrong.

original lines:

```
pub fn content_height_with_paginator(&self) -> usize {
        let content_len = self.content.read().unwrap().len();
        log::info!("content len: {content_len}");

        // add 1 more row for paginator if we can paginate
        if self.can_paginate() {
            content_len + 1
        } else {
            content_len
        }
    }

    fn can_paginate(&self) -> bool {
        let loaded = self.get_pagination().loaded_content();
        log::info!("can paginate: {loaded}");
        self.get_pagination().max_content().unwrap_or(0) > self.get_pagination().loaded_content()
    }

```

expected: upgrade fine.

updated lines: 

```
pub fn content_height_with_paginator(&self) -> usize {
        let content_len = self.content.read().unwrap().len();
        log::info!("content len: {}",content_len);

        // add 1 more row for paginator if we can paginate
        if self.can_paginate() {
            content_len + 1
        } else {
            content_len
        }
    }

    fn can_paginate(&self) -> bool {
        let loaded = self.get_pagination().loaded_content();
        log::info!("can paginate: {}",loaded);
        self.get_pagination().max_content().unwrap_or(0) > self.get_pagination().loaded_content()
    }
```

**System (please complete the following information):**
 - OS: Arch linux
 - Terminal: Alaritty
 - Version: 0.9.5
 - Installed from: AUR

**Comment by hrkfdn** [comment] 2022-01-23 16:23
Duplicate of #714

**Closed by hrkfdn** 2022-01-23 16:23 UTC
Labels: bug
