### ISSUE TITLE
Handle proxy server interruption gracefully

### ISSUE THREAD

**Issue by cyqsimon** [hrkfdn/ncspot#608] opened 2021-09-27 08:21 UTC
## The issue
I often find myself behind a firewall, therefore I usually run ncspot with an HTTP proxy. However sometimes due to various reasons the proxy needs to be restarted, either due to a configuration change or sometimes buggy behaviour. ncspot does not seem to be able to handle the interruption gracefully - when I restart the proxy server, ncspot would immediately crash with this error: `thread 'tokio-runtime-worker' panicked at 'Could not create session: IoError(Os { code: 111, kind: ConnectionRefused, message: "Connection refused" })', src/spotify.rs:192:14`.

I assume this is due to the brief downtime of the proxy server during its restart when the port is closed. While it makes sense from a naive programmatic POV (no connection, no service), practically it's probably not the desired behaviour. If it continues making connection attempts periodically, the error may (and in my case, would) soon go away.

Added to that, a hard crash causes all runtime configuration changes (i.e. current queue, volume, repeat flag, etc.) to be lost, which is inconvenient to say the least.

## To reproduce
1. Install and run privoxy, or a proxy server of your choice. I have only tested HTTP proxy but I suspect SOCKS proxy will have the same issue.
2. Set `http_proxy` and `https_proxy` environment variables.
3. Run ncspot and play any track.
4. Restart proxy server, and observe ncspot crash.

## Expected behaviour
A more graceful handling of the proxy service interruption, perhaps a text prompt followed by periodic reconnection attempts.

## System
 - OS: Manjaro KDE
 - Terminal: Yakuake
 - Version: 0.8.2
 - Installed from: AUR

## Logs

[stderr.log](https://github.com/hrkfdn/ncspot/files/7234538/stderr.log)
[stdout.log](https://github.com/hrkfdn/ncspot/files/7234539/stdout.log)

**Comment by mtshrmn** [comment] 2021-09-29 12:37
This is currently the biggest bug in ncspot. I've tried to reproduce it myself, but because I have no vpn or never thought of just disconnecting from the internet for a moment, I was never able to get it logged. I have no idea how to approach this bug.
A bad workaround I've come up with was to just quit (pressing `q`) after a system resume/vpn reconnection and have my state saved.

**Comment by hrkfdn** [comment] 2021-10-01 15:42
Indeed, it's hard to reproduce. I've tried it before and sometimes librespot simply does not detect that a session is stale and thus won't pass it on to ncspot, which makes it hard to impossible to handle it.

**Comment by hrkfdn** [comment] 2022-05-27 09:46
Duplicate of #628

**Closed by hrkfdn** 2022-05-27 09:46 UTC
Labels: bug
