### ISSUE TITLE
Music stops playing after connecting/disconnecting to VPN

### ISSUE THREAD

**Issue by Tejpal45** [hrkfdn/ncspot#264] opened 2020-09-04 03:33 UTC
I've noticed that whenever I disconenct or connect to a VPN if I'm using ncspot it stops working, the currently playing song will finish and I can still change songs and switch playlists and etc. but no song will actually play, it'll just stay stuck on 0:00 when the song is changed either by me or by the current song ending. 

I'm using ncspot version 0.2.1 on ArchLinux.

**Comment by gfbett** [comment] 2020-10-27 12:18
I have a similar issue, my vpn uses a proxy that does https traffic inspection, so the certificates are no longer valid, because the proxy regenerates the certificates (like a man in middle)
I guess nscpot is not using the system store for certificates, so all the connections fails

**Comment by Limero** [comment] 2020-12-20 12:15
I have a similar issue after resuming my computer after suspend, no VPN involved. ncspot 0.2.6 on both Arch Linux and Fedora 33.

Steps to replicate:
1. Start playing a song
2. Run `sudo systemctl suspend`
3. Wake up computer
4. The song will resume playback and finish, then display "Connecting to Spotify.." and not play the next song unless you manually switch song.

My guess is ncspot tries once to connect to Spotify before the internet connectivity has resumed and then doesn't try again until you switch the song yourself.

**Comment by hrkfdn** [comment] 2020-12-20 12:20
That's correct. This is already the "improved" behavior. So far I haven't
come up with an elegant way to detect/handle the disconnection, as it
mostly happens in the librespot layer.

**Comment by hrkfdn** [comment] 2022-05-27 09:46
I would love to fix it, but I can't really handle connectivity issues if librespot can't detect them yet. This hasn't changed.

Duplicate of #628

**Closed by hrkfdn** 2022-05-27 09:46 UTC
