### ISSUE TITLE
ncspot quits when after searching something you move to playlists tab

### ISSUE THREAD

**Issue by lulivi** [hrkfdn/ncspot#206] opened 2020-06-24 23:04 UTC
## Version info

item|info
---|---
ArchLinux| 5.7.4-arch1-1
AUR ncspot |`0.1.3`

## Steps to reproduce

1. Start ncspot in the terminal
2. Press `/` to search
3. Enter "ariana" and press `Return`
4. Move with `L` or `Right Arrow` to get to `Playlists` tab
5. When you are on `Playlists` tab it just quits.

## Config:

> ~/.config/ncspot/config.toml
```
[saved_state]
volume = 80
```

## Debug information

[debug.log](https://github.com/hrkfdn/ncspot/files/4828262/debug.log)

If you need any more information, just ask!
Thank you in advance.

**Comment by hrkfdn** [comment] 2020-06-25 19:29
Seems to work fine here, though I do see some playlists with emojis. Is your terminal able to handle those?

**Comment by lulivi** [comment] 2020-06-26 14:18
Mmm... Emojis work great in the terminal:

![image](https://user-images.githubusercontent.com/10894592/85866804-42c88080-b7c8-11ea-8ce6-4a61b4861a21.png)

 so no clue what it could be.

**Comment by lulivi** [comment] 2020-06-26 14:20
What I just realized is that, if I have music playing and I try to reproduce the steps I wrote before, the terminal quits, but the music keeps playing. Not sure if that helps to find the problem.

**Comment by hrkfdn** [comment] 2020-06-27 09:41
I'd need some more information as I can't reproduce this. Can you try getting a stacktrace, e.g. as such: `RUST_BACKTRACE=full cargo run -- -d /tmp/debug.log 2>>|/tmp/stderr.log`. It should be in /tmp/stderr.log.

If the music thread keeps going, it could indicate that something is with the ncurses interface. What terminal are you using?

**Comment by lulivi** [comment] 2020-06-27 15:47
I just discovered something. I usually run `ncspot` inside a `tmux` session. It seems the terminal detaches the session and keeps in the background (I can attach to it again).

**Comment by hrkfdn** [comment] 2020-07-08 20:31
Could have been fixed by a dependency update. I'll close it for now :)

**Closed by hrkfdn** 2020-07-08 20:31 UTC
