### ISSUE TITLE
ncspot 0.9.5 build failure

### ISSUE THREAD

**Issue by chenrui333** [hrkfdn/ncspot#716] opened 2022-01-20 17:21 UTC
👋 trying to build the latest release, but run into some build issue. The error log is as below:

<details>
<summary>build error</summary>

```
  error: there is no argument named `content_len`
    --> src/ui/listview.rs:88:34
     |
  88 |         log::info!("content len: {content_len}");
     |                                  ^^^^^^^^^^^^^

  error: there is no argument named `loaded`
     --> src/ui/listview.rs:100:35
      |
  100 |         log::info!("can paginate: {loaded}");
      |                                   ^^^^^^^^

  warning: unused import: `error`
   --> src/queue.rs:4:18
    |
  4 | use log::{debug, error, info};
    |                  ^^^^^
    |
    = note: `#[warn(unused_imports)]` on by default

  warning: `ncspot` (bin "ncspot") generated 1 warning
  error: failed to compile `ncspot v0.9.5 (/tmp/ncspot-20220119-18087-108fo7a/ncspot-0.9.5)`, intermediate artifacts can be found at `/tmp/ncspot-20220119-18087-108fo7a/ncspot-0.9.5/target`
```

</details>

full build log, https://github.com/Homebrew/homebrew-core/runs/4862263453
relates to Homebrew/homebrew-core#93389

**Comment by hrkfdn** [comment] 2022-01-20 18:10
Duplicate of #714

**Closed by hrkfdn** 2022-01-20 18:10 UTC
