### ISSUE TITLE
Skipping all tracks - Unable to play

### ISSUE THREAD

**Issue by Boxer66** [hrkfdn/ncspot#831] opened 2022-06-10 05:07 UTC
I have been having problems lately with ncspot in linux and windows with skipping tracks and unable to play songs.

This is not a ncspot issue but a librespot issue. Some have trouble with skipping tracks and crashing making ncspot unusable. The problem is the host that librespot connects to.  This has to do with a spesific host that librespot connects to but that can change anytime. 

To fix this force ap-gew4.spotify.com domain to point to the IP of ap-gew1.spotify.com, by setting this in hosts:  

104.199.65.124  ap-gew4.spotify.com.  

More info [here](https://github.com/librespot-org/librespot/issues/972).

**Comment by hrkfdn** [comment] 2022-06-10 20:25
Hey, unfortunately there's nothing I can do about this on the side of ncspot. I think this needs to be tackled upstream/in librespot.

Duplicate of #811

**Closed by hrkfdn** 2022-06-10 20:25 UTC
