### ISSUE TITLE
Last.fm Scrobbling (and now-playing) Support

### ISSUE THREAD

**Issue by AndydeCleyre** [hrkfdn/ncspot#35] opened 2019-03-15 21:31 UTC
I thought Spotify now implements scrobbling at an account level, independent of device or client, but maybe I'm wrong, as playing with ncspot (which I'm very excited about, thank you!) doesn't seem to result in scrobbles or now-playing information available to Last.fm.

I don't personally care if ncspot implements scrobbling internally or finds a way to get Spotify servers to do so, but I really need a music player to scrobble one way or another for me to use it.

Arch Linux, installed from AUR `ncspot-git` `0.0.0.98.3d385af-1`

Thanks for this project!

**Comment by GeorgeHJ** [comment] 2019-03-22 22:02
I can confirm I'm experiencing the same issue. It's definitely possible in my experience as a librespot user.

Likewise thanks!

**Comment by hrkfdn** [comment] 2019-03-23 09:39
Hmm, I can't find anything in Librespot that indicates scrobbling, but I only had a quick look. This could certainly be implemented in ncspot, though. Other than that, there is obviously not a lot of documentation on how to make use of the account-level scrobbling in Spotify.

**Comment by GeorgeHJ** [comment] 2019-03-23 10:05
I think account-level scrobbling is done directly on the corporate level. 

I think that implementing the now playing behaviour of other Spotify clients could hopefully bring about the scrobbling automatically.

**Comment by hrkfdn** [comment] 2019-03-23 10:13
The problem is it's not really documented anywhere. One major difference between the librespot application and ncspot is that librespot is a Spotify connect client, which uses a different interface. It could be that tracks are scrobbled because of Spotify connect.

**Comment by AndydeCleyre** [comment] 2019-05-14 19:58
FWIW, [rustfm-scrobble](https://crates.io/crates/rustfm-scrobble) exists.

**Comment by shurizzle** [comment] 2019-05-31 17:31
Take a look at https://github.com/mariusor/mpris-scrobbler

**Comment by treeshateorcs** [comment] 2019-09-03 07:46
https://github.com/InputUsername/rescrobbled

**Comment by AndydeCleyre** [comment] 2020-02-24 19:08
rescrobbled is indeed working well for me.

**Comment by hrkfdn** [comment] 2020-04-12 09:48
Possibly related: https://github.com/librespot-org/librespot/issues/342

**Comment by agiratech-vigneshm** [comment] 2020-05-22 14:39
@hrkfdn Do you think we can implement scrobbling outside of librespot using last.fm/libre.fm APIs directly? I am learning Rust for a month now, so I might give it a shot but I would like to know your thoughts on that direction and also do you think it is beginner friendly?

**Comment by hrkfdn** [comment] 2020-05-23 10:24
@agiratech-vigneshm Thanks for considering to contribute. Until this is implemented in librespot that could be a way to get ncspot to scrobble. I think it can be a beginner friendly task, especially if there is a nice crate that takes care of the AudioScrobbler protocol implementation. If you plan to submit this as a PR, can I ask you to implement in a way so it can be disabled/enabled with a cargo feature flag?

**Comment by AndydeCleyre** [comment] 2020-05-23 17:21
I'll just reiterate (maybe more clearly) that [rescrobbled](https://github.com/InputUsername/rescrobbled) is an entirely satisfactory solution for me personally.

**Comment by shivenigma** [comment] 2020-05-26 08:43
@hrkfdn Sorry I had to delete my previous comment about contributing because I accidentally commented from work account. I was planning to enable it as a config that the user can turn it on. I'll give it a try, 

@AndydeCleyre Thanks for letting us know, I'll give a try for rescrobbled and if it worked well for me, I'll just create a PR for updating the readme about the scroblling issue and using rescrobbled as a solution for now? how does that sounds for you?

**Comment by AndydeCleyre** [comment] 2020-05-28 18:05
@shivenigma :+1: That's good for me, thanks

**Comment by shivenigma** [comment] 2020-06-03 08:17
@AndydeCleyre I tried rescrobbled and it works really well and I haven't seen any issues with that. So now I am in a dilemma that whether ncSpot should replicate that again. Looking for suggestions on further action.

**Comment by AndydeCleyre** [comment] 2020-06-04 03:07
Don't look at me. As far as I'm concerned now, ncspot doesn't need it. But maybe others subscribed here can chime in . . . I'm using spotify-tui (along with rescrobbled) these days anyway.

**Comment by hrkfdn** [comment] 2020-06-16 22:48
Closing this as it should be fixed in librespot. Alternatively, [rescrobbled](https://github.com/InputUsername/rescrobbled) seems to do the trick.

**Closed by hrkfdn** 2020-06-16 22:48 UTC
Labels: enhancement
