### ISSUE TITLE
error[E0432]: unresolved import `syn::export` |  Error while building 

### ISSUE THREAD

**Issue by b0-ris** [hrkfdn/ncspot#387] opened 2021-01-13 15:14 UTC
### When i try to build ncspot ( cargo install ncspot) i get the following error message:

error[E0432]: unresolved import `syn::export`
  --> /home/boris/.cargo/registry/src/github.com-1ecc6299db9ec823/enumset_derive-0.5.0/src/lib.rs:10:10
   |
10 | use syn::export::Span;
   |          ^^^^^^ could not find `export` in `syn`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0432`.
error: could not compile `enumset_derive`

Caused by:
  process didn't exit successfully: `rustc --crate-name enumset_derive --edition=2018 /home/boris/.cargo/registry/src/github.com-1ecc6299db9ec823/enumset_derive-0.5.0/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type proc-macro --emit=dep-info,link -C prefer-dynamic -C embed-bitcode=no -C debug-assertions=off -C metadata=f1fdde2f1da49170 -C extra-filename=-f1fdde2f1da49170 --out-dir /tmp/cargo-installUyRwMv/release/deps -L dependency=/tmp/cargo-installUyRwMv/release/deps --extern darling=/tmp/cargo-installUyRwMv/release/deps/libdarling-98ccd3593390d2ba.rlib --extern proc_macro2=/tmp/cargo-installUyRwMv/release/deps/libproc_macro2-619a06f409ce1f0d.rlib --extern quote=/tmp/cargo-installUyRwMv/release/deps/libquote-aa0255829f72c1a9.rlib --extern syn=/tmp/cargo-installUyRwMv/release/deps/libsyn-ec04cc32b826e1c2.rlib --extern proc_macro --cap-lints allow` (exit code: 1)
warning: build failed, waiting for other jobs to finish...
error: failed to compile `ncspot v0.2.6`, intermediate artifacts can be found at `/tmp/cargo-installUyRwMv`

Caused by:
  build failed

* * *
Versions:
cargo 1.49.0 (d00d64df9 2020-12-05)
rustc 1.49.0 (e1884a8e3 2020-12-29)

**Comment by TheCatster** [comment] 2021-01-13 16:05
#385 is the solution as of now

**Comment by hrkfdn** [comment] 2021-01-13 17:04
Duplicate of #385

**Closed by hrkfdn** 2021-01-13 17:04 UTC
