### ISSUE TITLE
How can you navigate from search back to library

### ISSUE THREAD

**Issue by IanMacfarlane** [hrkfdn/ncspot#129] opened 2020-02-22 17:52 UTC
Once you search for something is there any way to get back to the library view?

**Comment by Kallestofeles** [comment] 2020-02-29 14:55
You can switch between queue, search and library views with F1, F2 and F3 respectively if that is what you mean.

**Comment by hrkfdn** [comment] 2020-03-05 10:22
Duplicate of https://github.com/hrkfdn/ncspot/issues/132

**Closed by hrkfdn** 2020-03-05 10:22 UTC
