### ISSUE TITLE
Missing requirements

### ISSUE THREAD

**Issue by antonioromero** [hrkfdn/ncspot#100] opened 2019-10-15 19:13 UTC
I needed also the following packages for Ubuntu 19.04:
`sudo apt install dbus-1-dev libdbus-1-dev libssl-dev libncurses-dev libpulse-dev`

So my complete installation process was:
```
 sudo apt install libxcb1-dev libxcb-render0-dev libxcb-shape0-dev libxcb-xfixes0-dev
 sudo apt install dbus-1-dev libdbus-1-dev libssl-dev libncurses-dev libpulse-dev
 git clone https://github.com/hrkfdn/ncspot.git
 cd ncspot/
 cargo build --release
```

**Comment by araghunde** [comment] 2019-11-05 15:45
The need for ```libdbus-1-dev```, ```libssl-dev``` and ```libncurses-dev``` is already specified in the README. Regarding ```libpulse-dev```, I think this is just a dupe of #96.

**Closed** 2019-11-06 18:04 UTC
