### ISSUE TITLE
Add the possibility to choose the audio output to the available device

### ISSUE THREAD

**Issue by XavierCLL** [hrkfdn/ncspot#143] opened 2020-02-29 19:41 UTC
Hi, first thank for the awesome app!

I always use spotify client in my laptop to control it to another device (such as sonos, google home, etc):

![image](https://user-images.githubusercontent.com/11801453/75613946-fe61f800-5ae7-11ea-8003-95fc22ec0629.png)

It would be a great idea to implement a menu to choose the device you want to control spotify

Thanks

**Comment by hrkfdn** [comment] 2020-03-01 09:31
Hey,

this is a duplicate of https://github.com/hrkfdn/ncspot/issues/101

Due to the massive changes it would require, Spotify connect support is currently not planned.

**Closed by hrkfdn** 2020-03-01 09:31 UTC
