### ISSUE TITLE
Inconsistent Keybindings

### ISSUE THREAD

**Issue by ohhskar** [hrkfdn/ncspot#178] opened 2020-04-15 12:10 UTC
Hello! I've been using ncspot for a few days and I found some parts of the software where the keybindings are inconsistent:
- In the help menu, moving up or down is not controlled by the keybindings that correspond to move up 1 or move down 1, but rather by the arrow keys.
- Same problem exists when opening songs. The dialog(?) box does not respect move up or move down keybindings

In addition, I cannot go back from the search menu using the back command. I cannot access my own playlists.

**Comment by hrkfdn** [comment] 2020-04-15 12:19
Duplicate of #108

**Closed by hrkfdn** 2020-04-15 12:19 UTC
