### ISSUE TITLE
No sound after suspend

### ISSUE THREAD

**Issue by daniel-vera-g** [hrkfdn/ncspot#176] opened 2020-04-07 17:42 UTC
After waking the system up from suspend, only the paused song is played.  
The following songs have no sound.
OS: Ubuntu 18.04
About suspend: https://help.ubuntu.com/stable/ubuntu-help/power-suspend.html.en

## How to reproduce

1. Open `ncspot`
1. Play song/s
1. Pause song and suspend system
1. Wake up
1. Play song -> Sound
1. Skip song -> No sound.

On `ncspot v0.1.2` and `ncspot v0.1.3`

https://github.com/hrkfdn/ncspot/issues/138 seems related, but I don't think so as everything works as expected before suspend.

**Comment by kris7t** [comment] 2020-04-28 17:52
It seems ncspot doesn't like when network access is interrupted. I could trigger the same behavior with simply disconnecting from wifi and connecting back. Also, spotifyd has a similar issue: https://github.com/Spotifyd/spotifyd/issues/573

**Comment by hrkfdn** [comment] 2020-06-16 22:45
Duplicate of https://github.com/hrkfdn/ncspot/issues/192

**Closed by hrkfdn** 2020-06-16 22:45 UTC
