### ISSUE TITLE
Request: Listen in other devices

### ISSUE THREAD

**Issue by LuisAVasquez** [hrkfdn/ncspot#319] opened 2020-11-13 17:09 UTC
On the Spotify official client, there is an option to listen from another devices available on the same LAN
Typical devices are:

- Other computers logged in

- Smarthphones and tablets

- Speakers

Could this functionality be implemented for ncspot?

Possibly helpful links:
[https://github.com/librespot-org/librespot/wiki/Options](url)
[https://developer.spotify.com/documentation/web-api/reference/player/get-a-users-available-devices/](url)
[https://github.com/librespot-org/librespot/wiki/Devices](url)

**Comment by hrkfdn** [comment] 2020-11-14 21:46
Duplicate of #83

**Closed by hrkfdn** 2020-11-14 21:46 UTC
