### ISSUE TITLE
ncspot does not close when terminal is closed

### ISSUE THREAD

**Issue by maru-sama** [hrkfdn/ncspot#1309] opened 2023-10-11 10:10 UTC
**Describe the bug**
The last commit a067ab2ae27e seems to break the way ncspot handles a SIGTERM. If I close the terminal ncspot continues to run and I have to kill it. Reverting this commit fixes this issue.

**To Reproduce**
1. Open ncspot in a terminal
2. Close the terminal
3. ncspot does not close

**Expected behavior**
ncspot should close as well, when the terminal is closed.

**System (please complete the following information):**
 - OS: Linux
 - Terminal: GNOME Terminal. kitty
 - Version: Master branch
 - Installed from: Compiled

**Comment by hrkfdn** [comment] 2023-10-11 13:26
Hey, thanks for the report. Can you let me know if it changes with the changes in #1310?

**Comment by hrkfdn** [comment] 2023-10-14 20:12
Duplicate of #1282 - it shouldn't stay open anymore but will cause a panic! when closing.

**Closed by hrkfdn** 2023-10-14 20:12 UTC
Labels: bug
